<a href="https://colab.research.google.com/github/Shashank1202/Deep_Learning/blob/main/LLMs/Transformer_and_Bert_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install transformers

In [3]:
from transformers import pipeline
classifier= pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [4]:
classifier("I'm very happy to learn new things everyday")

[{'label': 'POSITIVE', 'score': 0.9998760223388672}]

In [5]:
classifier("Worst hotels, all old food")

[{'label': 'NEGATIVE', 'score': 0.9997915625572205}]

In [6]:
results= classifier(["We are very happy to serve you",
                     "We hope you don't hate our service"])

for result in results:
  print(f"Label: {result['label']}, with score: {round(result['score'], 2)}")

Label: POSITIVE, with score: 1.0
Label: POSITIVE, with score: 0.87


In [7]:
classifier= pipeline('sentiment-analysis', model= "nlptown/bert-base-multilingual-uncased-sentiment")

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [9]:
classifier("la comida es mala")

[{'label': '1 star', 'score': 0.47258105874061584}]

In [11]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [12]:
model_name= "nlptown/bert-base-multilingual-uncased-sentiment"

model= TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt= True)
tokenizer= AutoTokenizer.from_pretrained(model_name)
classifier= pipeline('sentiment-analysis', model= model, tokenizer= tokenizer)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [13]:
classifier("Iam a good boy")

[{'label': '4 stars', 'score': 0.317687451839447}]

In [14]:
input= tokenizer("I'm very happy to learn new things everyday", return_tensors= "tf")

In [16]:
print(input)

{'input_ids': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=
array([[  101,   151,   112,   155, 12495, 19308, 10114, 34990, 10246,
        17994, 59811,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [17]:
tf_batch= tokenizer(
    ["I'm very happy to learn new things everyday",
     "I'm very sad to learn new things everyday"],
     padding= True,
     truncation= True,
     max_length= 512,
     return_tensors= "tf"
)

In [18]:
for key, value in tf_batch.items():
  print(f"{key}: {value.numpy().tolist()}")

input_ids: [[101, 151, 112, 155, 12495, 19308, 10114, 34990, 10246, 17994, 59811, 102], [101, 151, 112, 155, 12495, 14628, 10114, 34990, 10246, 17994, 59811, 102]]
token_type_ids: [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
