In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Let's Explore the Pytorch Library 

In [3]:
import torch

In [4]:
my_tensor= torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                       device="cpu", requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


In [5]:
print(torch.empty(size= (3, 3)))

tensor([[2.2914e+24, 4.3471e-41, 2.2914e+24],
        [4.3471e-41, 1.2281e+12, 3.3226e-41],
        [1.8931e+24, 4.3471e-41, 4.2830e+09]])


In [6]:
print(torch.zeros((3, 3)))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
print(torch.rand((3,3)))

tensor([[0.2963, 0.2138, 0.9693],
        [0.4571, 0.9704, 0.7517],
        [0.6143, 0.8684, 0.7882]])


In [8]:
print(torch.eye(5, 5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [9]:
print(torch.arange(start=0, end=5, step=1))

tensor([0, 1, 2, 3, 4])


In [10]:
print(torch.linspace(start=0.1, end=1, steps=10))

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [11]:
print(torch.empty(size=(1, 5)).normal_(mean=0,std=1))

tensor([[ 0.6311, -0.1947, -1.8775, -0.1062,  0.9886]])


In [12]:
print(torch.empty(size=(1, 5)).uniform_(0,1))

tensor([[0.7507, 0.4837, 0.9419, 0.5669, 0.8796]])


In [13]:
print(torch.diag(torch.ones(3)))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
tensor=torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [15]:
import numpy as np

np_array= np.zeros((5, 5))
print(np_array)
tensor= torch.from_numpy(np_array)
print(tensor)
print(tensor.numpy())

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
x=torch.tensor([1, 2, 3])
y= torch.tensor([9,8,7])

z1=torch.empty(3)
print(torch.add(x, y,out=z1))

print(x+y)

print(x-y)

print(torch.true_divide(x, y))

print(x*y)

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([ 9, 16, 21])


In [17]:
t=torch.zeros(3)
t.add_(x)
print(t)

tensor([1., 2., 3.])


In [18]:
z=x.pow(2)
print(z)

print(x**2)

tensor([1, 4, 9])
tensor([1, 4, 9])


In [19]:
z=x>0
print(z)

z=x<0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [20]:
#Matrix Multiplication

x1=torch.rand((2, 5))
x2=torch.rand((5, 3))
x3= torch.mm(x1, x2)
print(x1)
print(x2)
print(x3)

tensor([[0.3248, 0.9249, 0.6828, 0.4535, 0.3503],
        [0.1374, 0.6215, 0.6248, 0.0078, 0.9630]])
tensor([[0.3764, 0.8477, 0.7974],
        [0.8549, 0.2752, 0.4954],
        [0.1698, 0.4337, 0.7966],
        [0.2987, 0.9324, 0.0714],
        [0.0809, 0.0372, 0.3327]])
tensor([[1.1928, 1.2618, 1.4100],
        [0.7694, 0.6016, 1.2361]])


In [21]:
matrix_exp= torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[4.9025, 3.4363, 5.6215, 4.1537, 5.2616],
        [4.6929, 3.1660, 5.3842, 4.1355, 5.2545],
        [5.6942, 4.3028, 6.2271, 4.5232, 5.6319],
        [3.9995, 2.7845, 4.0719, 3.3880, 4.2696],
        [4.7105, 3.3300, 4.7069, 3.9941, 5.1085]])


In [22]:
z= torch.dot(x, y)
print(z)

tensor(46)


In [23]:
batch=32
n=10
m=20
p=30

tensor1= torch.rand((batch, n, m))
tensor2= torch.rand((batch,m,p))
out_bmm= torch.bmm(tensor1, tensor2)
print(out_bmm)

tensor([[[4.5088, 3.2780, 2.8397,  ..., 4.9433, 4.3436, 4.7862],
         [5.2909, 3.4418, 3.2953,  ..., 5.1406, 5.1087, 5.0551],
         [5.1144, 3.3181, 3.1856,  ..., 5.1533, 4.5513, 4.7147],
         ...,
         [4.7755, 3.8617, 3.6233,  ..., 5.7138, 4.3905, 5.7302],
         [3.6901, 2.2037, 2.3272,  ..., 3.2836, 2.9997, 4.3210],
         [5.2057, 3.6382, 3.6774,  ..., 5.3587, 5.1309, 5.8067]],

        [[4.9122, 6.2445, 4.5052,  ..., 4.9236, 6.0274, 6.4512],
         [4.0900, 5.6711, 4.2043,  ..., 4.3796, 6.1245, 5.8988],
         [4.9130, 5.9866, 4.8458,  ..., 5.3043, 6.1332, 4.9896],
         ...,
         [4.8947, 5.4408, 3.7913,  ..., 4.0218, 5.4185, 5.3448],
         [3.4986, 5.0512, 3.2493,  ..., 3.4094, 5.3593, 4.7728],
         [3.7146, 4.4966, 3.7165,  ..., 3.9415, 4.2131, 5.0210]],

        [[5.0169, 7.5268, 6.4445,  ..., 6.0362, 7.2279, 5.2535],
         [3.2716, 4.6567, 4.5796,  ..., 3.8840, 4.8198, 3.5809],
         [4.4948, 6.6264, 5.3586,  ..., 4.6803, 6.6326, 4.

In [24]:
#Example of BroadCasting

x1=torch.rand((5, 5))
x2= torch.rand((1, 5))

print(x1-x2)

tensor([[ 0.1481,  0.0843,  0.4138,  0.6728,  0.2351],
        [ 0.0117, -0.7313,  0.2191,  0.4044, -0.2563],
        [-0.1199, -0.1802, -0.0429,  0.1289, -0.4557],
        [ 0.7286,  0.1089,  0.1384,  0.8145,  0.1177],
        [ 0.6158,  0.0668,  0.2274,  0.6266, -0.3493]])


In [25]:
print(x1**x2)

tensor([[0.8486, 0.9563, 0.9044, 0.9790, 0.9205],
        [0.7778, 0.1757, 0.8340, 0.9479, 0.5433],
        [0.5361, 0.7210, 0.6828, 0.8906, 0.3414],
        [0.9804, 0.9777, 0.7975, 0.9914, 0.8393],
        [0.9629, 0.9410, 0.8375, 0.9745, 0.4554]])


In [26]:
#Other useful operations

sum_x= torch.sum(x, dim=0)
print(sum_x)

tensor(6)


In [27]:
values, indices= torch.max(x, dim=0)
print(values, indices)

tensor(3) tensor(2)


In [28]:
values, indices= torch.min(x, dim=0)
print(values, indices)

tensor(1) tensor(0)


In [29]:
abs_x= torch.abs(x)
print(abs_x)

tensor([1, 2, 3])


In [30]:
z= torch.argmax(x, dim=0)
print(z)

tensor(2)


In [31]:
z= torch.argmin(x, dim=0)
print(z)

tensor(0)


In [32]:
mean_x= torch.mean(x.float(), dim=0)
print(mean_x)

tensor(2.)


In [33]:
z= torch.eq(x, y)
print(z)

tensor([False, False, False])


In [34]:
sort=torch.sort(y, dim=0, descending=False)
print(sort)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))


In [35]:
z=torch.clamp(x, min=0, max=2)
print(z)

tensor([1, 2, 2])


In [36]:
x=torch.tensor([1,0,1,1,1], dtype=torch.bool)
print(x)

tensor([ True, False,  True,  True,  True])


In [37]:
print(torch.any(x))

tensor(True)


In [38]:
print(torch.all(x))

tensor(False)


In [39]:
#Tensor Indexing

batch_size=10
features=25
x=torch.rand((batch_size, features))
print(x[0].shape)

torch.Size([25])


In [40]:
print(x[:, 0].shape)

torch.Size([10])


In [41]:
print(x[2, 0:10])

tensor([0.9819, 0.3459, 0.5315, 0.1114, 0.1650, 0.0425, 0.9143, 0.6013, 0.1233,
        0.8092])


In [42]:
x= torch.rand([3, 5])
rows= torch.tensor([1, 0])
cols= torch.tensor([4, 0])
print(x[rows, cols])

tensor([0.4589, 0.9407])


In [43]:
# More Advanced indexing

x= torch.arange(10)
print(x[(x<2) |(x>8)])

tensor([0, 1, 9])


In [44]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [45]:
#Usefull operations

print(torch.where(x > 5, x, x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [46]:
print(torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique())

tensor([0, 1, 2, 3, 4])


In [47]:
print(x.ndimension())

1


In [48]:
print(x.numel())

10


In [49]:
#Tensor Reshaping

x=torch.arange(9)

x_3X3= x.view(3, 3)
x_3X3= x.reshape(3, 3)
print(x_3X3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [50]:
y= x_3X3.t()
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [51]:
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [52]:
x1= torch.rand((2, 5))
x2= torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)

torch.Size([4, 5])


In [53]:
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([2, 10])


In [54]:
z= x1.view(-1)
print(z.shape)

torch.Size([10])


In [55]:
batch= 64
x= torch.rand((batch, 2, 5))
z- x.view(batch, -1)
print(z.shape)

torch.Size([10])


In [56]:
z= x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 5, 2])


In [57]:
x= torch.arange(10)
print(x.unsqueeze(0).shape)

torch.Size([1, 10])


In [58]:
print(x.unsqueeze(1).shape)

torch.Size([10, 1])


In [59]:
x= torch.arange(10).unsqueeze(0).unsqueeze(1)
z= x.squeeze(1)
print(z.shape)

torch.Size([1, 10])


# The End